out_dir: results
metric_best: ap
metric_agg: argmax
wandb:
  use: False
  project: scratch  # W&B project for debugging runs.
dataset:
  format: PyG-DEL_v4
  name: PCQM4Mv2-inference
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+RWSE
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  edge_encoder_bn: False
pretrained:
  dir: pretrained/pcqm4m-GPS+RWSE.deep
  reset_prediction_head: False
train:
  mode: PCQM4Mv2-inference
  batch_size: 256
model:
  type: GPSModel
  loss_fun: cross_entropy
  graph_pooling: mean
gnn:
  head: san_graph
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  batchnorm: True
  act: gelu
  dropout: 0.0
